--No nosso trabalho a conex�o � SYSTEM
--SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM DUAL; Identifica o nome da conex�o

/*Apaga os relacionamentos*/
ALTER TABLE SYSTEM.COMANDAS DROP CONSTRAINT CLIENTES_COMANDAS_FK;
ALTER TABLE SYSTEM.ITENS_COMANDA DROP CONSTRAINT COMANDAS_ITENS_COMANDA_FK;

/*Apaga as tabelas */
DROP TABLE SYSTEM.CLIENTES;
DROP TABLE SYSTEM.COMANDAS;
DROP TABLE SYSTEM.ITENS_COMANDA;

/*Apaga as sequences*/
DROP SEQUENCE SYSTEM.COMANDAS_ID_COMANDA_SEQ;
DROP SEQUENCE SYSTEM.ITENS_COMANDA_ID_ITEM_COMANDA_SEQ;

/*Criando as tabelas */
CREATE TABLE SYSTEM.CLIENTES (
                CPF_CLIENTE VARCHAR(11) NOT NULL,
                NOME_CLIENTE VARCHAR(255) NOT NULL,
                TELEFONE_CLIENTE VARCHAR(11) NOT NULL,
                EMAIL_CLIENTE VARCHAR(100) NOT NULL,
                CONSTRAINT CPF PRIMARY KEY (CPF_CLIENTE)
);

-- SELECT * FROM SYSTEM.CLIENTES; -- Consulta table completa
-- DELETE FROM SYSTEM.CLIENTES; -- Deleta todos os registros da tabela

CREATE TABLE SYSTEM.COMANDAS (
                ID_COMANDA INTEGER NOT NULL,
                DATA_COMANDA DATE NOT NULL,
                STATUS_COMANDA VARCHAR(50) NOT NULL,
                CPF_CLIENTE VARCHAR(11) NOT NULL,
                CONSTRAINT ID_COMANDA PRIMARY KEY (ID_COMANDA)
);


CREATE TABLE SYSTEM.ITENS_COMANDA (
                ID_ITEM_COMANDA INTEGER NOT NULL,
                QTD_ITEM NUMERIC NOT NULL,
                DESCRICAO_PRODUTO VARCHAR(255) NOT NULL,
                VALOR_UNITARIO_ITEM NUMERIC(9,2) NOT NULL,
                ID_COMANDA INTEGER NOT NULL,
                CONSTRAINT ITENS_COMANDA_ID PRIMARY KEY (ID_ITEM_COMANDA)
);

/*Cria as sequences
CPF n�o ser� criado sequencialmente, pois � um valor digitado pelo usu�rio
*/
CREATE SEQUENCE SYSTEM.COMANDAS_ID_COMANDA_SEQ;
CREATE SEQUENCE SYSTEM.ITENS_COMANDA_ID_ITEM_COMANDA_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE SYSTEM.COMANDAS ADD CONSTRAINT CLIENTES_COMANDAS_fk
FOREIGN KEY (CPF_CLIENTE)
REFERENCES SYSTEM.CLIENTES (CPF_CLIENTE)
NOT DEFERRABLE;

ALTER TABLE SYSTEM.ITENS_COMANDA ADD CONSTRAINT COMANDAS_ITENS_COMANDA_fk
FOREIGN KEY (ID_COMANDA)
REFERENCES SYSTEM.COMANDAS (ID_COMANDA)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON SYSTEM.CLIENTES TO SYSTEM;
GRANT ALL ON SYSTEM.COMANDAS TO SYSTEM;
GRANT ALL ON SYSTEM.ITENS_COMANDA TO SYSTEM;

ALTER USER SYSTEM quota unlimited on USERS;
